cache_dir: ./data/

setting:
  # ------------ 查询玩家UID使用的cookie列表 ------------
  #必须设置才能使用 可以登录米游社 获取cookie 主要内容为 account_id=******; cookie_token=*********;
  cookies:
    - account_id=; cookie_token=;